# Generated by Django 4.1.2 on 2022-10-19 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdraw')], max_length=10)),
                ('amount', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('validated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transferApp.profile')),
            ],
        ),
    ]
