# Generated by Django 4.1.2 on 2022-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0003_remove_history_validated_remove_profile_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='transaction_type',
            field=models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdraw')], max_length=20),
        ),
    ]
