# Generated by Django 4.1.2 on 2022-10-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0004_alter_history_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='transferApp.profile'),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_type',
            field=models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdraw'), ('TR', 'Transfer')], max_length=20),
        ),
    ]
