# Generated by Django 4.1.2 on 2022-10-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferApp', '0005_history_receiver_alter_history_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('SS', 'Success'), ('FL', 'Fail')], default=('SS', 'Success'), max_length=10),
        ),
    ]
